name: Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    # 🔥 Install dependencies
    - name: Install dependencies
      run: npm install

    # 🔥 Build React app
    - name: Build React app
      run: npm run build

    # 🔥 Verify build
    - name: Check build folder
      run: ls -la build

    # AWS Login
    - name: AWS Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Login to ECR
    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | \
        docker login --username AWS --password-stdin 421826136489.dkr.ecr.ap-south-1.amazonaws.com

    # 🔥 Build Image (UPDATED)
    - name: Build Image
      run: docker build -t react-app:${{ github.sha }} .

    # 🔥 Tag Image (UPDATED)
    - name: Tag Image
      run: docker tag react-app:${{ github.sha }} 421826136489.dkr.ecr.ap-south-1.amazonaws.com/react-app:${{ github.sha }}

    # 🔥 Push Image (UPDATED)
    - name: Push Image
      run: docker push 421826136489.dkr.ecr.ap-south-1.amazonaws.com/react-app:${{ github.sha }}

    # Deploy ECS
    - name: Deploy ECS
      run: |
        aws ecs update-service \
        --cluster react-app-cluster \
        --service react-service \
        --force-new-deployment
